function dLM1da1 = fse_dLM1da1(F1,F2,a1,a2,alpha,beta)
%FSE_DLM1DA1
%    DLM1DA1 = FSE_DLM1DA1(F1,F2,A1,A2,ALPHA,BETA,LAMBDA1)

%    This function was generated by the Symbolic Math Toolbox version 5.6.
%    10-Jan-2014 14:29:43

syms lambda1;

t118 = F2.*a1;
t115 = F1-t118;
t120 = alpha.*t115;
t116 = beta-t120;
t117 = exp(t116);
t119 = a2-1.0;
t121 = t117+1.0;
dLM1da1 = -lambda1+(F2.*t119)./t121+F2.*alpha.*t115.*t117.*t119.*1.0./t121.^2;
