function dM1da1 = fse_dM1da1(F1,F2,a1,a2,alpha,beta)
%FSE_DM1DA1
%    DM1DA1 = FSE_DM1DA1(F1,F2,A1,A2,ALPHA,BETA)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Nov-2015 04:33:30

t5 = F2.*a1;
t2 = F1-t5;
t7 = alpha.*t2;
t3 = beta-t7;
t4 = exp(t3);
t6 = a2-1.0;
t8 = t4+1.0;
dM1da1 = (F2.*t6)./t8+F2.*alpha.*t2.*t4.*t6.*1.0./t8.^2;
