function dM1da2 = fse_dM1da2(F1,F2,a1,alpha,beta)
%FSE_DM1DA2
%    DM1DA2 = FSE_DM1DA2(F1,F2,A1,ALPHA,BETA)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Nov-2015 04:33:30

t2 = F1-F2.*a1;
dM1da2 = -t2./(exp(beta-alpha.*t2)+1.0);
